### ISSUE TITLE
Check Release Action: Upload release assets as artifacts?

### ISSUE THREAD

**Issue by jtpio** [jupyter-server/jupyter_releaser#135]
### Problem

The [Check Release Action](https://github.com/jupyter-server/jupyter_releaser#check-release-workflow) is really convenient to validate the repo is compatible with the releaser.

Wondering whether we could also upload the release assets as GitHub Actions artifacts? So they could be downloaded if needed, just to double check. The tarball would contain both the Python and npm packages if available.

### Proposed Solution

Extend the check release action to upload built assets as artifacts.

### Additional context

**Comment by jtpio** [comment]
Maybe adding the following snippet to the end of the check release workflow is enough actually:

```yaml
- name: Upload Distributions
  uses: actions/upload-artifact@v2
  with:
      name: releaser-dist-${{ github.run_number }}
      path: .jupyter_releaser_checkout/dist
```

Which could be documented in the README: https://github.com/jupyter-server/jupyter_releaser#checklist-for-adoption
